ZEN-33021 ZenOperator can save device Priority when changing Prod. State
zenoss/zenoss-prodbin pull request #3902
Opened 2020-09-08 14:50 UTC by romanbakaleyko

2020-09-08 15:18 UTC, romanbakaleyko commented
* disabled rows on the device overview user doesn't have access to
* check role explicitly for changing production state
* set context in the device grid for user without global role
* removed some code in the Action.js as it is broken and causes a problem because once externallyDisabled is set to true there is no way to set it back to false. Since I couldn't figure out what role this thing plays instead of fixing it I removed it.

Did some some and for me things work fine.

2020-09-09 12:25 UTC, jpeacock-zenoss requested changes

2020-09-09 12:25 UTC, jpeacock-zenoss commented on Products/ZenUI3/browser/resources/js/zenoss/Action.js
>              if (!this.permitted && !this.filtered) {
This `if` statement will never succeed or never execute because the `if` statement on line 21 will return when `this.permitted` is false.

2020-09-10 14:45 UTC, jpeacock-zenoss approved these changes

2020-09-10 16:28 UTC, merged