Handle and log the UnicodeDecodeError
zenoss/zenoss-prodbin pull request #4133
Opened 2022-04-05 20:18 UTC by d-terletskyi

Fixes ZEN-32208.

To handle the issue with UnicodeDecodeError the decoding procedure was
modified by adding additional checks. The procedure tries to decode
values using zCollectorDecoding if it is defined, otherwise, it tries to
apply the utf-8 and then latin-1encodings simultaneously logging
information about this. If decoding of the value in strict mode causes
errors, then it will be done in ignore mode, therefore non-Unicode
symbols will be ignored.

2022-04-12 16:09 UTC, jpeacock-zenoss requested changes

2022-04-12 16:09 UTC, jpeacock-zenoss commented on Products/DataCollector/ApplyDataMap/datamaputils.py
> +
Now that I've had some time to think about this issue and review your changes in response to our original conversation, I think a different strategy will have some benefits.

After relearning that the `decode` method has an `errors` argument, I think the strategy of trying to guess the encoding is more work than necessary to accomplish our goal.  The goal of the `_decode_value` function is to normalize strings to the system's default encoding.  For troubleshooting purposes, a side goal would be to log when specifying `zCollectorDecoding` would be helpful for decoding the value.  Another thing to note is that we've configured `sys.getdefaultencoding` to return "utf-8" as the default codec (have a look at /opt/zenoss/lib/python2.7/sitecustomize.py in an image).

So, maybe an implementation like the following will suffice:
```
    try:
        value = value.decode(codec)
    except UnicodeDecodeError as ex:
        value = value.decode(codec, errors="ignore")
        log.warn(
            "Unable to decode string using codec '%s'.  "
            "Using a modified string without errors.  "
            "Please set zCollectorDecoding to the correct codec. "
            "object=%r modified-value='%s' error=%s",
            codec, obj, value, ex,
        )
            
    return value.encode(sys.getdefaultencoding())
```

2022-04-12 16:32 UTC, d-terletskyi commented on Products/DataCollector/ApplyDataMap/datamaputils.py
> +            "zCollectorDecoding.")
Understood

2022-04-12 16:32 UTC, d-terletskyi commented on Products/DataCollector/ApplyDataMap/datamaputils.py
> +        codec = obj.zCollectorDecoding
Understood.

2022-04-12 16:36 UTC, d-terletskyi commented on Products/DataCollector/ApplyDataMap/datamaputils.py
> +                 codec, ex1)
Do you mean we need to write into the log only one final message after the decoding/encoding resolution?

2022-04-12 17:34 UTC, jpeacock-zenoss commented on Products/DataCollector/ApplyDataMap/datamaputils.py
> +                 codec, ex1)
Yes.  Like in the example code I wrote below.

2022-04-13 13:54 UTC, d-terletskyi commented
The fix was improved according to all remarks and suggestions noted above.

2022-04-13 14:02 UTC, jpeacock-zenoss requested changes

2022-04-13 14:23 UTC, d-terletskyi commented
The text of the warning was slightly modified, according to the remark noted above.

2022-04-13 14:25 UTC, jpeacock-zenoss approved these changes

2022-04-13 14:53 UTC, merged