ZEN-33965: Solr data migration from 7.7.3 to 8.11.1
zenoss/zenoss-prodbin pull request #4134
Opened 2022-04-06 14:49 UTC by Deer-WarLord

2022-04-06 18:08 UTC, StevePC requested changes

2022-04-06 18:08 UTC, StevePC commented on Products/ZenModel/migrate/updateSolrConfigs.py
> +            service.configFiles.append(cfg_obj)
should probably verify these don't already exist before appending them

2022-04-06 18:08 UTC, StevePC commented on Products/ZenModel/migrate/updateSolrConfigs.py
> +        # TODO add snapshot.0
remove comment, as done elsewhere

2022-04-07 08:05 UTC, Deer-WarLord commented on Products/ZenModel/migrate/updateSolrConfigs.py
> +    version = Migrate.Version(SCHEMA_MAJOR, SCHEMA_MINOR, SCHEMA_REVISION)
Before the release, we will have a build to change these constants, for all migration scripts in this release. 
The same will be for that migration https://github.com/zenoss/zenoss-prodbin/commit/d5a54bbb8cc595898aaa0c97ff187ec0500d791c

2022-04-07 14:36 UTC, StevePC approved these changes

2022-04-08 09:38 UTC, merged