Feature/zen 33996: Fix adding events with an empty summary
zenoss/zenoss-prodbin pull request #4145
Opened 2022-04-19 09:24 UTC by d-terletskyi

2022-04-20 14:00 UTC, Deer-WarLord approved these changes

2022-04-20 14:53 UTC, jpeacock-zenoss requested changes

2022-04-20 14:53 UTC, jpeacock-zenoss commented on Products/ZenRRD/zencommand.py
> +                "Task paused  device=%s ip=%s interval=%s error=%s",
This message is not correct.  There is no "pausing" occurring in this exception handler.

2022-04-20 14:53 UTC, jpeacock-zenoss commented on Products/ZenRRD/zencommand.py
> +        except defer.CancelledError:
I'm not convinced that just catching CancelledError is a complete fix.  We don't know why the deferred was cancelled.  Simply logging "deferred was cancelled" provides no useful information to whoever is troubleshooting the message.

2022-04-21 11:06 UTC, d-terletskyi commented
The fix was changed according to the remarks noted above.

2022-04-21 20:25 UTC, d-terletskyi commented
The fix was changed according to the remarks noted above.

2022-04-21 20:28 UTC, jpeacock-zenoss approved these changes

2022-04-27 08:17 UTC, merged