Feature: ZEN-34387
zenoss/zenoss-prodbin pull request #4238
Opened 2023-05-16 18:10 UTC by zensaiello

2023-05-16 18:10 UTC, webhookbotuser commented
Can one of the admins verify this patch?

2023-05-16 18:10 UTC, webhookbotuser commented
Can one of the admins verify this patch?

2023-05-16 18:10 UTC, webhookbotuser commented
Can one of the admins verify this patch?

2023-05-25 14:17 UTC, StevePC requested changes

2023-05-25 14:17 UTC, StevePC commented on Products/ZenEvents/TrapFilter.py
> +            filtersByLevel[key] = filterDef
need to unindent to preserve logic

2023-05-25 14:17 UTC, StevePC commented on Products/ZenEvents/TrapFilter.py
> +            filtersByLevel[oid] = filterDef
unindent as well

2023-06-01 17:38 UTC, StevePC requested changes

2023-06-01 17:38 UTC, StevePC commented on Products/ZenModel/migrate/zentrapSvcDefForFiltering.py
> +            if fc.content == ofc.content:
unlikely but ofc could be None here

2023-06-01 18:39 UTC, StevePC approved these changes

2023-06-06 07:16 UTC, Deer-WarLord commented
1. If we're applying a new configuration to the services, shouldn't that also be defined in the zenoss-service repo?
2. Maybe it's worth applying the new graph config through the JSON file instead of direct [Python objects configuration](https://github.com/zenoss/zenoss-prodbin/pull/4238/files#diff-1e95c880eaef298fa9a2232b676022018f4771c595fb4ffe43dacd47bc0f1e5fR125-R171)?

2023-06-19 07:09 UTC, Deer-WarLord approved these changes

2023-06-20 16:18 UTC, jpeacock-zenoss commented
please test this

2023-06-20 21:22 UTC, merged