ZEN-34366: allow -replacement and -addition templates for non-ZPL dev…
zenoss/zenoss-prodbin pull request #4240
Opened 2023-06-06 19:20 UTC by StevePC

…ices and components.  This will require an update to ZPL's DeviceBase.getRRDTemplates() which assumes replaced templates have not already been removed from the list

2023-06-06 19:20 UTC, webhookbotuser commented
Can one of the admins verify this patch?

2023-06-06 19:20 UTC, webhookbotuser commented
Can one of the admins verify this patch?

2023-06-06 19:20 UTC, webhookbotuser commented
Can one of the admins verify this patch?

2023-06-06 20:04 UTC, zensaiello requested changes

2023-06-06 20:04 UTC, zensaiello commented on Products/ZenModel/Device.py
> +                templates.append(template)
This code block logic is replaced by 418-419, 'Only add if -replacement named template does not exist' ?

2023-06-20 08:28 UTC, Deer-WarLord requested changes

2023-06-20 08:28 UTC, Deer-WarLord commented on Products/ZenModel/IpInterface.py
> +                templates.append(template)
Don't we need to check whether the template is none?

2023-06-20 08:28 UTC, Deer-WarLord commented on Products/ZenModel/MetricMixin.py
> +            default = self.getRRDTemplateByName(defaultName)
Why do we get **default** only if the replacement is none? Shouldn't the approach be the same as for IpInterface.py?

2023-06-20 13:47 UTC, jpeacock-zenoss requested changes

2023-06-20 13:47 UTC, jpeacock-zenoss commented on Products/ZenModel/Device.py
> +                #    self.zDeviceTemplates + [replacement.titleOrId()])
Commented out code should be removed.  It's not doing anything and doesn't help explain (to me) the surrounding code.

2023-06-20 13:47 UTC, jpeacock-zenoss commented on Products/ZenModel/Device.py
> +                #    self.zDeviceTemplates + [addition.titleOrId()])
Same thing about commented out code.

2023-06-20 15:13 UTC, zensaiello approved these changes

2023-06-20 15:32 UTC, Deer-WarLord approved these changes

2023-06-20 15:45 UTC, StevePC reviewed
retest this please

2023-06-20 16:02 UTC, jpeacock-zenoss approved these changes

2023-06-20 17:46 UTC, merged