Improve zproxy metrics collection reliability
zenoss/zenoss-prodbin pull request #4480
Opened 2024-07-02 14:14 UTC by odubrovyk

Fixes ZEN-34680.

Added last change record for Zope config files.
Now we are comparing the returned last modified value
with a recorded last change value.

2024-07-02 14:16 UTC, odubrovyk commented
@StevePC Could you please take a look at this PR?

2024-07-03 13:56 UTC, StevePC requested changes

2024-07-03 13:56 UTC, StevePC commented on bin/metrics/zenossStatsView.py
> +                self.last_changed[upstream_file] = now
while this will work, shouldn't we store upstream_modified instead, since we have it?

2024-07-03 16:04 UTC, StevePC approved these changes

2024-07-03 16:25 UTC, merged